config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  resources :users
  resource :sessions, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index]

  get '/tags/hashtags/:name', to:'tags#hashtags'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  has_and_belongs_to_many :tags, dependent: :destroy

  validates :text, :user, presence: true
  validates :text, length: { maximum: 255 }

  before_save :question_tag_create

  def create_tags_from_answer_and_text
      tag = text.scan(/#[\p{L}0-9_]{1,55}/)
      tag << self.answer.scan(/#[\p{L}0-9_]{1,55}/) if self.answer.present?
      tag
  end

  def question_tag_create
    self.tags.clear
    create_tags_from_answer_and_text.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.to_s.downcase.delete('[]#""'))
      self.tags << tag unless tag.nil?
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:edit, :update, :destroy]
  before_action :authorize_user, except: [:create, :hashtags]
  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  def create
    @question = Question.new(question_params)
    @question.author = current_user if current_user.present?


    if check_captcha(@question) && @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос задан'
    else
      render :edit
    end
  end

  def hashtags
    tag = Tag.find_by(name: params[:name])
    @questions = tag.questions
  end

  # PATCH/PUT /questions/1
  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Вопрос сохранен'
    else
      render :edit
    end
  end

  # DELETE /questions/1
  def destroy
    user = @question.user
    @question.destroy
    redirect_to user_path(user), notice: 'Вопрос удален'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def load_question
    @question = Question.find(params[:id])
  end



  def authorize_user
    reject_user unless @question.user == current_user
  end

  # Only allow a trusted parameter "white list" through.
  def question_params
    if current_user.present? &&
        params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer)
    else
      params.require(:question).permit(:user_id, :text)
    end
  end

  def check_captcha(model)
    current_user.present? || verify_recaptcha(model: model)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def render_with_question(text)
    text.gsub(/#[\p{L}0-9_]{1,55}/){|word| link_to word, "/tags/hashtags/#{word.delete('#').downcase}"}.html_safe
  end
end

app/views/questions/_form.html.erb
<div class="form">
  <%# Форма для объекта @question %>
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%# Скрытое поле — айдишник юзера, кому задается вопрос %>
    <%= f.hidden_field :user_id %>

    <div class="form-field">
      <%= f.label :text, 'Вопрос', class: 'form-label' %>
      <%= f.text_area :text, class: 'form-textarea' %>
    </div>

    <%# Простая авторизация - может ли текущий юзер править вопрос? %>
    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
        <%= f.label :answer, 'Ответ', class: 'form-label' %>
        <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>

    <%= recaptcha_tags unless current_user.present? %>

    <div class="form-action buffer-both">
      <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      или
      <%= link_to "вернуться", user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<% question ||= nil %>
<% action_icon = question.answer.blank? ? 'reply' : 'pencil' %>


<div class="question">
  <div class="question-content">
    <div class="question-text text-lead">
        <%= render_with_question(question.text) %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= render_with_question(question.answer) if question.answer.present? %>
      </div>
    <% end %>
    <div class="question-date">
      <%= l(question.created_at, format: :short) %>
    </div>

    <div class="question-text">
      <% if question.author.present? %>
        <span class="text-small">Автор: </span>
        <%= link_to "@#{question.author.username}", user_path(question.author) %>
      <% else %>
        anonymous
      <% end %>

      <span class="text-small">&ensp; Вопрос задан пользователю: </span>
      <%= link_to "#{question.user.username}", user_path(question.user) %>
    </div>
  </div>

  <% if question.user == current_user %>
    <div class="question-actions">
      <%= link_to fa_icon(action_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question),
                  method: :delete, data: {confirm: 'Точно удалить вопрос?'} %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <%= render 'form' %>
  </div>
</div>

app/views/questions/hashtags.html.erb
<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>